# Generated by Django 3.0.3 on 2021-08-03 06:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[100, 100], upload_to='seasonal/category/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SeasonalApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон номер')),
                ('video_by_user', models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('video_link', models.CharField(blank=True, help_text='Ссылка на видео для публикации', max_length=255, null=True, verbose_name='Ютуб ссылка')),
                ('cover_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='seasonal/apartment/', verbose_name='Обложка')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Провереннный')),
                ('type', models.CharField(choices=[('1', 'Обычный'), ('2', 'Премиум'), ('3', 'Благотворительность')], max_length=20, verbose_name='Тип')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonal.Category', verbose_name='Категория')),
                ('favorites', models.ManyToManyField(related_name='seasonal_favorites', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('views', models.ManyToManyField(related_name='apartment_views', to=settings.AUTH_USER_MODEL, verbose_name='Просмотров')),
                ('watched_videos', models.ManyToManyField(related_name='watcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пансионат',
                'verbose_name_plural': 'Пансионаты',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=255, null=True, verbose_name='Ютуб ссылка')),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='seasonal/stories/', verbose_name='Обложка')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.ManyToManyField(related_name='stories_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сторис',
                'verbose_name_plural': 'Сторисы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ViewStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='seasonal.Stories', verbose_name='Сторис видео')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр сториса',
                'verbose_name_plural': 'Просмотры сторисов',
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='seasonal.SeasonalApartment', verbose_name='Ютуб ссылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр видео',
                'verbose_name_plural': 'Просмотры видео',
            },
        ),
        migrations.CreateModel(
            name='SeasonalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='seasonal.SeasonalApartment', verbose_name='Ютуб ссылка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='seasonal.SeasonalComment', verbose_name='Родитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('room_limit', models.IntegerField(verbose_name='Колличество номеров')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='seasonal.SeasonalApartment', verbose_name='Пансионат')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='ComplaintStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=2, verbose_name='Тип жалобы')),
                ('text', models.TextField(blank=True, null=True)),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_stories', to='seasonal.Stories', verbose_name='Сторис видео')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_stories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на сторис',
                'verbose_name_plural': 'Жалобы на сторисы',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата въезда')),
                ('exit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата выезда')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('adult_count', models.IntegerField(verbose_name='Количество взрослых')),
                ('kids_count', models.IntegerField(verbose_name='Количество детей')),
                ('room_count', models.IntegerField(verbose_name='Количество номеров')),
                ('total_price', models.IntegerField(verbose_name='Сумма брони')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='seasonal.Room', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на заселение',
                'verbose_name_plural': 'Заявки на заселение',
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seasonal/image/', verbose_name='Изображение')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seasonal.SeasonalApartment', verbose_name='Пансинат')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Список изображений',
            },
        ),
        migrations.CreateModel(
            name='LikeStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_stories', to='seasonal.Stories', verbose_name='Сторис видео')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_stories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк сториса',
                'verbose_name_plural': 'Лайки сторисов',
                'unique_together': {('user', 'stories')},
            },
        ),
    ]
