# Generated by Django 3.0.3 on 2021-08-05 07:09

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название города')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[100, 100], upload_to='seasonal/city/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='seasonalapartment',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seasonal.City', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
