# Generated by Django 3.0.3 on 2021-08-03 06:44

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Pass valid phone number', regex='^996\\d{9}$')], verbose_name='Телефон')),
                ('otp', models.CharField(max_length=4, verbose_name='SMS code')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('method', models.CharField(choices=[('o_money', 'O! Money'), ('balance', 'Balance'), ('mega_pay', 'Mega Pay'), ('o_balance', 'O balance'), ('beeline_balance', 'Beeline balance'), ('megacom_balance', 'Megacom balance')], max_length=20, verbose_name='method')),
                ('requisite', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 996XXX123456.', regex='^996\\d{9}$')], verbose_name='Requisite')),
                ('batch', models.CharField(max_length=256, verbose_name='batch')),
                ('status', models.CharField(choices=[('unprocessed', 'unprocessed'), ('successful', 'success'), ('error', 'error')], default='unprocessed', max_length=20, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.BooleanField(default=False, verbose_name='Агент Статус')),
                ('gender', models.CharField(blank=True, max_length=30, verbose_name='Пол')),
                ('region', models.CharField(blank=True, choices=[('1', 'Ош'), ('2', 'Ысык-Кол'), ('3', 'Жалал-Абад'), ('4', 'Талас'), ('5', 'Баткен'), ('6', 'Нарын'), ('7', 'Чуй'), ('8', 'Бишкек')], max_length=10, null=True, verbose_name='Регион')),
                ('view_count', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('balance', models.FloatField(default=0, verbose_name='Остаток баланса')),
                ('withdrawn_balance', models.FloatField(default=0, verbose_name='Cнятый баланс')),
                ('image', models.ImageField(blank=True, default='user/profile_photo.png', null=True, upload_to='user', verbose_name='Фотография')),
                ('birth_date', models.DateField(default=datetime.datetime.now, verbose_name='День рождения')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт профиль',
                'verbose_name_plural': 'Аккаунт профиль',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тело')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[150, 150], upload_to='notifications/', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created',),
            },
        ),
    ]
