# Generated by Django 3.0.3 on 2020-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agent',
            field=models.BooleanField(default=False, verbose_name='Agent Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user/profile_photo.png', null=True, upload_to='user'),
        ),
    ]
