# Generated by Django 3.0.3 on 2020-02-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_withdrawn_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
