# Generated by Django 3.0.3 on 2020-03-10 08:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Аккаунт профиль', 'verbose_name_plural': 'Аккаунт профиль'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agent',
            field=models.BooleanField(default=False, verbose_name='Агент Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Остаток баланса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user/profile_photo.png', null=True, upload_to='user', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновление'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='withdrawn_balance',
            field=models.FloatField(default=0, verbose_name='Cнятый баланс'),
        ),
    ]
