# Generated by Django 3.0.3 on 2020-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='receiver',
            field=models.CharField(max_length=50),
        ),
    ]
