# Generated by Django 3.0.3 on 2020-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_auto_20200225_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
