# Generated by Django 3.0.3 on 2020-03-10 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0004_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'verbose_name': 'Касса', 'verbose_name_plural': 'Касса'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо код', 'verbose_name_plural': 'Промо коды'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='method',
            field=models.CharField(max_length=50, verbose_name='Метод'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='operator',
            field=models.CharField(max_length=50, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='props_number',
            field=models.CharField(max_length=255, verbose_name='Пропс номер'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver',
            field=models.CharField(max_length=50, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
