# Generated by Django 3.0.3 on 2021-08-09 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0002_videoview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('phone_1', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон номер 1')),
                ('video', models.CharField(help_text='Просмотр видео', max_length=255, null=True, verbose_name='Ютуб ссылка')),
                ('is_top', models.BooleanField(default=False, verbose_name='Топ')),
                ('image', models.ImageField(upload_to='videos/', verbose_name='Обложка')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Провереннный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories2', to='video.Category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users2', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='block',
        ),
        migrations.DeleteModel(
            name='Videoview',
        ),
    ]
