# Generated by Django 3.0.3 on 2021-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210809_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request2',
            old_name='phone_1',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='request2',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='request2',
            name='status',
            field=models.CharField(choices=[('1', 'Отклонено'), ('2', 'Активно'), ('3', 'В ожидании')], default='3', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Отклонено'), ('2', 'Активно'), ('3', 'В ожидании')], default='3', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
