# Generated by Django 3.0.3 on 2020-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
