# Generated by Django 3.0.3 on 2021-08-09 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20210809_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='request2',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
