# Generated by Django 3.0.3 on 2020-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20200226_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media/training_video/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
