# Generated by Django 3.0.3 on 2020-02-26 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_videotraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotraining',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='videos_training/'),
            preserve_default=False,
        ),
    ]
