# Generated by Django 3.0.3 on 2020-02-29 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_videotraining_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='block',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/banners/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
