# Generated by Django 3.0.3 on 2020-02-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20200229_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(),
        ),
    ]
