# Generated by Django 3.0.3 on 2020-03-10 08:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0014_auto_20200229_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='videotraining',
            options={'verbose_name': 'Видео обучения', 'verbose_name_plural': 'Видео обучения'},
        ),
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name': 'Просмотр история', 'verbose_name_plural': 'Просмотр истории'},
        ),
        migrations.AddField(
            model_name='video',
            name='facebook',
            field=models.CharField(max_length=30, null=True, verbose_name='Файсбук'),
        ),
        migrations.AddField(
            model_name='video',
            name='instagram',
            field=models.CharField(max_length=30, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='video',
            name='phone_1',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон номер 1'),
        ),
        migrations.AddField(
            model_name='video',
            name='phone_2',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон номер 2'),
        ),
        migrations.AddField(
            model_name='video',
            name='phone_3',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон номер 3'),
        ),
        migrations.AddField(
            model_name='video',
            name='web_site',
            field=models.CharField(max_length=30, null=True, verbose_name='Вебсайт'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='block',
            field=models.IntegerField(default=1, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(upload_to='media/banners/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.Video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='reply',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='video.Comment', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='video.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='request',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Провереннный'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Промо код'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='video.Video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='views',
            field=models.IntegerField(verbose_name='Просмотр'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='videos/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_top',
            field=models.BooleanField(default=True, verbose_name='Топ'),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='video',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/videos/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='videotraining',
            name='image',
            field=models.ImageField(upload_to='videos_training/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='videotraining',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='videotraining',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='videotraining',
            name='video',
            field=models.FileField(upload_to='media/training_video/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='video.Video', verbose_name='Видео'),
        ),
    ]
