# Generated by Django 3.0.3 on 2020-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_auto_20200310_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Файсбук'),
        ),
        migrations.AlterField(
            model_name='video',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='video',
            name='phone_1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон номер 1'),
        ),
        migrations.AlterField(
            model_name='video',
            name='phone_2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон номер 2'),
        ),
        migrations.AlterField(
            model_name='video',
            name='phone_3',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон номер 3'),
        ),
        migrations.AlterField(
            model_name='video',
            name='web_site',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вебсайт'),
        ),
    ]
