# Generated by Django 3.0.3 on 2020-03-10 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0016_auto_20200310_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name': 'Просмотр история (Реклама))', 'verbose_name_plural': 'Просмотр истории (Реклама)'},
        ),
        migrations.CreateModel(
            name='ViewBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='video.Banner', verbose_name='Баннер видео')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр история (Баннер)',
                'verbose_name_plural': 'Просмотр истории (Баннер)',
            },
        ),
    ]
