# Generated by Django 3.0.3 on 2020-03-10 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0018_auto_20200310_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='views',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
