# Generated by Django 3.0.3 on 2020-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_banner_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.CharField(max_length=255, null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=255, null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='videotraining',
            name='video',
            field=models.CharField(max_length=255, null=True, verbose_name='Видео'),
        ),
    ]
